# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\liziy\Desktop\62_SenBlePSoC_AbandonSerialDialogUI_Perfect\PSoC_Ble\04_SenOpticalFlowPixelsOTA _ Refine\SenOpticalFlowPixelsOTA.cydsn\SenOpticalFlowPixelsOTA.cyprj
# Date: Thu, 31 Mar 2016 20:26:33 GMT
#set_units -time ns
create_clock -name {UART_SCBCLK(FFB)} -period 729.16666666666663 -waveform {0 364.583333333333} [list [get_pins {ClockBlock/ff_div_1}]]
create_clock -name {SPI_Master_SCBCLK(FFB)} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/ff_div_2}]]
create_clock -name {PrISM_Clock_1(FFB)} -period 1000 -waveform {0 500} [list [get_pins {ClockBlock/ff_div_7}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFCLK} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {UART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 35 71} [list]
create_generated_clock -name {SPI_Master_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 3 5} [list]
create_generated_clock -name {PrISM_Clock_1} -source [get_pins {ClockBlock/hfclk}] -edges {1 49 97} [list]
create_generated_clock -name {PrISM_Clock} -source [get_pins {ClockBlock/hfclk}] -edges {1 97 193} [list [get_pins {ClockBlock/udb_div_0}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\Users\liziy\Desktop\62_SenBlePSoC_AbandonSerialDialogUI_Perfect\PSoC_Ble\04_SenOpticalFlowPixelsOTA _ Refine\SenOpticalFlowPixelsOTA.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\liziy\Desktop\62_SenBlePSoC_AbandonSerialDialogUI_Perfect\PSoC_Ble\04_SenOpticalFlowPixelsOTA _ Refine\SenOpticalFlowPixelsOTA.cydsn\SenOpticalFlowPixelsOTA.cyprj
# Date: Thu, 31 Mar 2016 20:26:28 GMT
